name: FE-CI/CD

on:
  push:
    branches: ["CI/CD_Test"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¢ ê¹ƒí—ˆë¸Œ Checkout !!
        uses: actions/checkout@v3

      - name: ğŸ“¢ Docker ì´ë¯¸ì§€ ë¹Œë“œ
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/zibi-frontserver .

      - name: ğŸ“¢ DockerHub ë¡œê·¸ì¸
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: ğŸ“¢  DockerHubì— Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/zibi-frontserver

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: ğŸ“¢ EC2ì— ë°°í¬
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            echo "âœ… EC2 ì—°ê²° ì„±ê³µ!"
            cd ~/zibi
            
            echo "âœ… Docker ì´ë¯¸ì§€ Pull"
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/zibi-frontserver
            
            echo "âœ… ê¸°ì¡´ ì»¨í…Œì´ë„ˆ ì¤‘ì§€ ë° ì‚­ì œ"
            docker compose down || true
            
            echo "âœ… ìƒˆ ì»¨í…Œì´ë„ˆ ì‹¤í–‰"!
            docker compose up -d --build
            
            echo "âœ… ë°°í¬ ì™„ë£Œ!"
